security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_platform:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppCustomAuthenticator
                - App\Security\GoogleAuthenticator
            entry_point: App\Security\AppCustomAuthenticator
            user_checker: App\Security\UserChecker
            logout:
                path: app_logout
                target: /login

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/auth/google, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/products, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/categories, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/resend-verification, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer/contact, roles: PUBLIC_ACCESS }
        - { path: ^/api/customer, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: IS_AUTHENTICATED }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/verify-email, roles: PUBLIC_ACCESS }
        - { path: ^/check-email, roles: PUBLIC_ACCESS }
        - { path: ^/verify-email-code, roles: PUBLIC_ACCESS }
        - { path: ^/resend-verification, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/product, roles: ROLE_STAFF }
        - { path: ^/category, roles: ROLE_STAFF }
        - { path: ^/change-password, roles: [ROLE_USER, ROLE_STAFF] }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/staff, roles: ROLE_STAFF }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_STAFF]
        ROLE_STAFF: ROLE_USER
